### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/crlfmt#8]
Failure below when saving this file:

``` go
package sql

func lol()
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4018d9]

goroutine 1 [running]:
panic(0x4fd560, 0xc42000e0e0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.checkPath(0xc42006a0c0, 0x12, 0x51e415, 0x3, 0xc42003bd01)
        /go/src/github.com/cockroachdb/crlfmt/main.go:129 +0x2f9
main.main.func1(0xc42006a0c0, 0x12, 0x59f1c0, 0xc420075450, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/crlfmt/main.go:81 +0xbd
path/filepath.walk(0xc42006a0c0, 0x12, 0x59f1c0, 0xc420075450, 0xc42006a160, 0x0, 0x1)
        /usr/local/go/src/path/filepath/path.go:351 +0x81
path/filepath.Walk(0xc42006a0c0, 0x12, 0xc42006a160, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:398 +0xd5
main.main()
        /go/src/github.com/cockroachdb/crlfmt/main.go:87 +0x28f
```

**Comment by benesch** [comment]
This was fixed in 5d85b323a.
